In [1]:
import pandas as pd
import numpy as np

In [3]:
df=pd.read_csv('top5leagues-1.csv')
df.head()

,Rk,Player,Nation,Pos,Squad,Age,Born,90s,Gls,Sh,...,Dist,FK,PK,PKatt,xG,npxG,npxG/Sh,G-xG,np:G-xG,Matches
0,1,Max Aarons,eng ENG,DF,Bournemouth,23,2000,13.7,0,2,...,23.9,0,0,0,0,0,0.02,0,0,Matches
1,2,Joshua Acheampong,eng ENG,DF,Chelsea,17,2006,0.1,0,0,...,NaN,0,0,0,0,0,NaN,0,0,Matches
2,3,Tyler Adams,us USA,MF,Bournemouth,24,1999,1.3,0,0,...,NaN,0,0,0,0,0,NaN,0,0,Matches
3,4,Tosin Adarabioyo,eng ENG,DF,Fulham,25,1997,18,2,14,...,14.2,0,0,0,0.7,0.7,0.05,1.3,1.3,Matches
4,5,Elijah Adebayo,eng ENG,FW,Luton Town,25,1998,15.8,10,31,...,9.6,0,0,0,5.9,5.9,0.19,4.1,4.1,Matches

In [7]:

duplicates=df[df.duplicated(subset=['Player'], keep=False)]
print(duplicates['Player'].unique())

['Player' 'Cameron Archer' 'Armando Broja' 'Alex Iwobi' 'Brennan Johnson'
 'Neal Maupay' 'James Mcatee' 'Matheus Nunes' 'Cole Palmer'
 'Kalvin Phillips' 'Sergio Reguilón']

In [12]:
duplicates = df[df['Player'].isin(duplicates['Player'].unique())]
duplicates.head(30)

,Rk,Player,Nation,Pos,Squad,Age,Born,90s,Gls,Sh,...,Dist,FK,PK,PKatt,xG,npxG,npxG/Sh,G-xG,np:G-xG,Matches
30,30,Cameron Archer,eng ENG,"FW,MF",Sheffield Utd,22,2001,20.4,4,42,...,16.7,0,0,0,5.5,5.5,0.14,-1.5,-1.5,Matches
31,31,Cameron Archer,eng ENG,MF,Aston Villa,22,2001,0.1,0,0,...,NaN,0,0,0,0,0,NaN,0,0,Matches
75,74,Armando Broja,al ALB,FW,Chelsea,21,2001,5,1,13,...,11.1,0,0,0,2.4,2.4,0.18,-1.4,-1.4,Matches
76,75,Armando Broja,al ALB,FW,Fulham,21,2001,1,0,0,...,NaN,0,0,0,0,0,NaN,0,0,Matches
256,248,Alex Iwobi,ng NGA,MF,Everton,27,1996,1.6,0,4,...,16.2,0,0,0,0.3,0.3,0.08,-0.3,-0.3,Matches
257,249,Alex Iwobi,ng NGA,"FW,MF",Fulham,27,1996,24.4,5,51,...,18.5,0,0,0,5.3,5.3,0.1,-0.3,-0.3,Matches
269,260,Brennan Johnson,wls WAL,FW,Tottenham,22,2001,23.2,5,50,...,12.9,0,0,0,10.3,10.3,0.21,-5.3,-5.3,Matches
270,261,Brennan Johnson,wls WAL,"FW,MF",Nott'ham Forest,22,2001,2.6,0,3,...,19.7,0,0,0,0.3,0.3,0.11,-0.3,-0.3,Matches
346,334,Neal Maupay,fr FRA,FW,Brentford,26,1996,14.7,6,37,...,15.3,1,0,0,5.7,5.7,0.16,0.3,0.3,Matches
347,335,Neal Maupay,fr FRA,FW,Everton,26,1996,1.2,0,5,...,12.5,0,0,0,1.4,1.4,0.29,-1.4,-1.4,Matches
350,338,James Mcatee,eng ENG,"MF,FW",Sheffield Utd,20,2002,20.2,3,25,...,18.6,2,1,1,3.1,2.3,0.09,-0.1,-0.3,Matches
351,339,James Mcatee,eng ENG,MF,Manchester City,20,2002,0,0,0,...,NaN,0,0,0,0,0,NaN,0,0,Matches
398,384,Matheus Nunes,pt POR,MF,Wolves,24,1998,2,0,1,...,15.4,0,0,0,0.1,0.1,0.08,-0.1,-0.1,Matches
399,385,Matheus Nunes,pt POR,MF,Manchester City,24,1998,7.3,0,9,...,17.9,0,0,0,0.8,0.8,0.09,-0.8,-0.8,Matches
429,414,Cole Palmer,eng ENG,"FW,MF",Chelsea,21,2002,29,22,100,...,22.1,11,9,9,18.2,11.1,0.11,3.8,1.9,Matches
430,415,Cole Palmer,eng ENG,MF,Manchester City,21,2002,0.1,0,0,...,NaN,0,0,0,0,0,NaN,0,0,Matches
443,427,Kalvin Phillips,eng ENG,MF,West Ham,27,1995,3.4,0,3,...,25.8,0,0,0,0.1,0.1,0.03,-0.1,-0.1,Matches
444,428,Kalvin Phillips,eng ENG,MF,Manchester City,27,1995,1,0,2,...,21.7,0,0,0,0.1,0.1,0.04,-0.1,-0.1,Matches
461,445,Sergio Reguilón,es ESP,DF,Manchester Utd,26,1996,4.6,0,4,...,18.1,0,0,0,0.2,0.2,0.05,-0.2,-0.2,Matches
462,446,Sergio Reguilón,es ESP,DF,Brentford,26,1996,12.4,0,13,...,18.2,0,0,0,0.8,0.8,0.06,-0.8,-0.8,Matches

In [11]:
df=df[df['Player']!='Player']

In [25]:
df.set_index('Rk', inplace=True)
df.head(50)

,Player,Nation,Pos,Squad,Age,Born,90s,Gls,Sh,SoT,...,Dist,FK,PK,PKatt,xG,npxG,npxG/Sh,G-xG,np:G-xG,Matches
Rk,,,,,,,,,,,,,,,,,,,,,
1,Max Aarons,eng ENG,DF,Bournemouth,23,2000,13.7,0,2,0,...,23.9,0,0,0,0,0,0.02,0,0,Matches
2,Joshua Acheampong,eng ENG,DF,Chelsea,17,2006,0.1,0,0,0,...,NaN,0,0,0,0,0,NaN,0,0,Matches
3,Tyler Adams,us USA,MF,Bournemouth,24,1999,1.3,0,0,0,...,NaN,0,0,0,0,0,NaN,0,0,Matches
4,Tosin Adarabioyo,eng ENG,DF,Fulham,25,1997,18,2,14,5,...,14.2,0,0,0,0.7,0.7,0.05,1.3,1.3,Matches
5,Elijah Adebayo,eng ENG,FW,Luton Town,25,1998,15.8,10,31,14,...,9.6,0,0,0,5.9,5.9,0.19,4.1,4.1,Matches
6,Simon Adingra,ci CIV,FW,Brighton,21,2002,24.7,6,52,22,...,15.9,0,0,0,4.3,4.3,0.08,1.7,1.7,Matches
7,Nayef Aguerd,ma MAR,DF,West Ham,27,1996,20.6,1,14,3,...,10.8,0,0,0,1.5,1.5,0.11,-0.5,-0.5,Matches
8,Brandon Aguilera,cr CRC,FW,Nott'ham Forest,20,2003,0.1,0,0,0,...,NaN,0,0,0,0,0,NaN,0,0,Matches
9,Naouirou Ahamada,fr FRA,"MF,FW",Crystal Palace,21,2002,3.9,0,9,2,...,20.4,0,0,0,0.5,0.5,0.05,-0.5,-0.5,Matches
10,Anel Ahmedhodžić,ba BIH,DF,Sheffield Utd,24,1999,29.4,2,19,5,...,11.9,0,0,0,3.1,3.1,0.17,-1.1,-1.1,Matches
11,Ola Aina,ng NGA,DF,Nott'ham Forest,26,1996,18.8,1,11,1,...,26.6,0,0,0,0.3,0.3,0.02,0.7,0.7,Matches
12,Rayan Aït-Nouri,dz ALG,"DF,MF",Wolves,22,2001,25.9,2,24,8,...,16.8,0,0,0,3.3,3.3,0.14,-1.3,-1.3,Matches
13,Kristoffer Ajer,no NOR,DF,Brentford,25,1998,20.4,2,12,4,...,9.9,0,0,0,1.3,1.3,0.11,0.7,0.7,Matches
14,Manuel Akanji,ch SUI,"DF,MF",Manchester City,28,1995,27.9,2,15,5,...,17,0,0,0,1.9,1.9,0.13,0.1,0.1,Matches
15,Nathan Aké,nl NED,DF,Manchester City,28,1995,22.7,2,20,5,...,10.8,0,0,0,2.5,2.5,0.12,-0.5,-0.5,Matches
16,Thiago Alcántara,es ESP,MF,Liverpool,32,1991,0.1,0,0,0,...,NaN,0,0,0,0,0,NaN,0,0,Matches
17,Trent Alexander-Arnold,eng ENG,DF,Liverpool,24,1998,23.9,3,47,8,...,24.4,5,0,0,2.6,2.3,0.05,0.4,0.7,Matches
18,Alisson,br BRA,GK,Liverpool,30,1992,28,0,0,0,...,NaN,0,0,0,0,0,NaN,0,0,Matches
19,Miguel Almirón,py PAR,FW,Newcastle Utd,29,1994,21.5,3,41,12,...,16.1,0,0,0,4.5,4.5,0.11,-1.5,-1.5,Matches
20,Edson Álvarez,mx MEX,MF,West Ham,25,1997,26.4,1,17,3,...,21.1,0,0,0,1.3,1.3,0.08,-0.3,-0.3,Matches
21,Julián Álvarez,ar ARG,"MF,FW",Manchester City,23,2000,29.4,11,96,37,...,17.8,13,2,2,13,11.5,0.12,-2,-2.5,Matches
22,Zeki Amdouni,ch SUI,FW,Burnley,22,2000,21.7,5,48,21,...,17.8,0,1,1,5.8,5,0.1,-0.8,-1,Matches
23,Sofyan Amrabat,ma MAR,"MF,DF",Manchester Utd,26,1996,10.4,0,3,0,...,26.1,0,0,0,0.1,0.1,0.02,-0.1,-0.1,Matches
24,Joachim Andersen,dk DEN,DF,Crystal Palace,27,1996,37.9,2,21,8,...,12.8,1,0,0,1.7,1.7,0.08,0.3,0.3,Matches
25,Elliot Anderson,eng ENG,"MF,FW",Newcastle Utd,20,2002,11.4,0,19,4,...,14.5,0,0,0,1.5,1.5,0.08,-1.5,-1.5,Matches
26,Jaidon Anthony,eng ENG,FW,Bournemouth,23,1999,1.7,0,2,1,...,24.5,0,0,0,0.1,0.1,0.03,-0.1,-0.1,Matches
27,Michail Antonio,jm JAM,FW,West Ham,33,1990,18.8,6,30,14,...,13.1,0,0,0,5.8,5.8,0.19,0.2,0.2,Matches
28,Antony,br BRA,FW,Manchester Utd,23,2000,14.7,1,43,15,...,18.9,0,0,0,3.4,3.4,0.08,-2.4,-2.4,Matches
29,Oliver Arblaster,eng ENG,MF,Sheffield Utd,19,2004,10.5,0,1,1,...,16.6,0,0,0,0,0,0.04,0,0,Matches
30,Cameron Archer,eng ENG,"FW,MF",Sheffield Utd,22,2001,20.4,4,42,9,...,16.7,0,0,0,5.5,5.5,0.14,-1.5,-1.5,Matches
31,Cameron Archer,eng ENG,MF,Aston Villa,22,2001,0.1,0,0,0,...,NaN,0,0,0,0,0,NaN,0,0,Matches
32,Alphonse Areola,fr FRA,GK,West Ham,30,1993,30,0,0,0,...,NaN,0,0,0,0,0,NaN,0,0,Matches
33,Lorenz Assignon,tg TOG,DF,Burnley,23,2000,13.7,1,9,4,...,22.1,0,0,0,0.4,0.4,0.04,0.6,0.6,Matches
34,Serge Aurier,ci CIV,"DF,MF",Nott'ham Forest,30,1992,9.3,0,6,1,...,16,0,0,0,0.2,0.2,0.03,-0.2,-0.2,Matches
35,Taiwo Awoniyi,ng NGA,FW,Nott'ham Forest,25,1997,11.6,6,22,11,...,11.5,0,0,0,4.7,4.7,0.22,1.3,1.3,Matches
36,Jordan Ayew,gh GHA,"FW,MF",Crystal Palace,31,1991,28.3,4,48,19,...,18.2,0,0,0,3.9,3.9,0.08,0.1,0.1,Matches
37,Benoît Badiashile,fr FRA,DF,Chelsea,22,2001,14.9,0,6,1,...,14.1,0,0,0,0.3,0.3,0.05,-0.3,-0.3,Matches
38,Leon Bailey,jm JAM,"MF,FW",Aston Villa,25,1997,23,10,53,18,...,16.1,1,0,0,6.3,6.3,0.12,3.7,3.7,Matches
39,Stefan Bajcetic,es ESP,MF,Liverpool,18,2004,0.3,0,0,0,...,NaN,0,0,0,0,0,NaN,0,0,Matches
40,George Baldock,gr GRE,DF,Sheffield Utd,30,1993,10.8,0,1,0,...,22.2,0,0,0,0,0,0.02,0,0,Matches
41,Carlos Baleba,cm CMR,MF,Brighton,19,2004,14.7,0,21,5,...,24.4,0,0,0,0.8,0.8,0.04,-0.8,-0.8,Matches
42,Fodé Ballo-Touré,sn SEN,"DF,MF",Fulham,26,1997,0.8,0,0,0,...,NaN,0,0,0,0,0,NaN,0,0,Matches
43,Shandon Baptiste,gd GRN,MF,Brentford,25,1998,2.5,1,2,2,...,6.6,0,0,0,0.9,0.9,0.45,0.1,0.1,Matches
44,Valentín Barco,ar ARG,"DF,FW",Brighton,19,2004,3.4,0,4,2,...,24.2,0,0,0,0.2,0.2,0.05,-0.2,-0.2,Matches
45,Ross Barkley,eng ENG,MF,Luton Town,29,1993,29.1,5,66,19,...,21.5,6,0,0,4.1,4.1,0.06,0.9,0.9,Matches
46,Harvey Barnes,eng ENG,"FW,MF",Newcastle Utd,25,1997,8.9,5,27,12,...,16,0,0,0,3.6,3.6,0.13,1.4,1.4,Matches
47,Chris Basham,eng ENG,"DF,MF",Sheffield Utd,35,1988,3.6,0,2,0,...,10.8,0,0,0,0.1,0.1,0.06,-0.1,-0.1,Matches
48,Calvin Bassey,ng NGA,DF,Fulham,23,1999,25.6,1,5,1,...,10.1,0,0,0,0.3,0.3,0.07,0.7,0.7,Matches
49,Owen Beck,wls WAL,DF,Liverpool,20,2002,0.1,0,0,0,...,NaN,0,0,0,0,0,NaN,0,0,Matches
50,Donny van de Beek,nl NED,DF,Manchester Utd,26,1997,0,0,1,0,...,16.1,0,0,0,0,0,0.04,0,0,Matches

In [27]:

df.drop(columns='Matches',axis=1,inplace=True)
df.columns

C:\Users\user\AppData\Local\Temp\ipykernel_17816\3154929989.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(columns='Matches',axis=1,inplace=True)

Index(['Player', 'Nation', 'Pos', 'Squad', 'Age', 'Born', '90s', 'Gls', 'Sh',
       'SoT', 'SoT%', 'Sh/90', 'SoT/90', 'G/Sh', 'G/SoT', 'Dist', 'FK', 'PK',
       'PKatt', 'xG', 'npxG', 'npxG/Sh', 'G-xG', 'np:G-xG'],
      dtype='object')

In [29]:
import re
def nation_fix(nation):
    nat_fixed=re.findall(r'[A-Z]',nation)
    nat_fixed=''.join(nat_fixed)
    return nat_fixed

vec_func=np.vectorize(nation_fix)
df['Nation']=vec_func(df['Nation'])

C:\Users\user\AppData\Local\Temp\ipykernel_17816\2548870112.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Nation']=vec_func(df['Nation'])

In [30]:
df.head()

,Player,Nation,Pos,Squad,Age,Born,90s,Gls,Sh,SoT,...,G/SoT,Dist,FK,PK,PKatt,xG,npxG,npxG/Sh,G-xG,np:G-xG
Rk,,,,,,,,,,,,,,,,,,,,,
1,Max Aarons,ENG,DF,Bournemouth,23,2000,13.7,0,2,0,...,NaN,23.9,0,0,0,0,0,0.02,0,0
2,Joshua Acheampong,ENG,DF,Chelsea,17,2006,0.1,0,0,0,...,NaN,NaN,0,0,0,0,0,NaN,0,0
3,Tyler Adams,USA,MF,Bournemouth,24,1999,1.3,0,0,0,...,NaN,NaN,0,0,0,0,0,NaN,0,0
4,Tosin Adarabioyo,ENG,DF,Fulham,25,1997,18,2,14,5,...,0.4,14.2,0,0,0,0.7,0.7,0.05,1.3,1.3
5,Elijah Adebayo,ENG,FW,Luton Town,25,1998,15.8,10,31,14,...,0.71,9.6,0,0,0,5.9,5.9,0.19,4.1,4.1

In [32]:
df.fillna(0,inplace=True)
df.head()

C:\Users\user\AppData\Local\Temp\ipykernel_17816\499839367.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.fillna(0,inplace=True)

,Player,Nation,Pos,Squad,Age,Born,90s,Gls,Sh,SoT,...,G/SoT,Dist,FK,PK,PKatt,xG,npxG,npxG/Sh,G-xG,np:G-xG
Rk,,,,,,,,,,,,,,,,,,,,,
1,Max Aarons,ENG,DF,Bournemouth,23,2000,13.7,0,2,0,...,0,23.9,0,0,0,0,0,0.02,0,0
2,Joshua Acheampong,ENG,DF,Chelsea,17,2006,0.1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,Tyler Adams,USA,MF,Bournemouth,24,1999,1.3,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,Tosin Adarabioyo,ENG,DF,Fulham,25,1997,18,2,14,5,...,0.4,14.2,0,0,0,0.7,0.7,0.05,1.3,1.3
5,Elijah Adebayo,ENG,FW,Luton Town,25,1998,15.8,10,31,14,...,0.71,9.6,0,0,0,5.9,5.9,0.19,4.1,4.1

In [33]:
df.to_csv('top5leagues_final.csv')