In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('top5leagues.csv')
df.head()

,Unnamed: 0_level_0,Unnamed: 1_level_0,Unnamed: 2_level_0,Unnamed: 3_level_0,Unnamed: 4_level_0,Unnamed: 5_level_0,Unnamed: 6_level_0,Unnamed: 7_level_0,Standard,Standard.1,...,Standard.8,Standard.9,Standard.10,Standard.11,Expected,Expected.1,Expected.2,Expected.3,Expected.4,Unnamed: 25_level_0
0,Rk,Player,Nation,Pos,Squad,Age,Born,90s,Gls,Sh,...,Dist,FK,PK,PKatt,xG,npxG,npxG/Sh,G-xG,np:G-xG,Matches
1,1,Max Aarons,eng ENG,DF,Bournemouth,23,2000,13.7,0,2,...,23.9,0,0,0,0.0,0.0,0.02,0.0,0.0,Matches
2,2,Joshua Acheampong,eng ENG,DF,Chelsea,17,2006,0.1,0,0,...,NaN,0,0,0,0.0,0.0,NaN,0.0,0.0,Matches
3,3,Tyler Adams,us USA,MF,Bournemouth,24,1999,1.3,0,0,...,NaN,0,0,0,0.0,0.0,NaN,0.0,0.0,Matches
4,4,Tosin Adarabioyo,eng ENG,DF,Fulham,25,1997,18.0,2,14,...,14.2,0,0,0,0.7,0.7,0.05,+1.3,+1.3,Matches

In [27]:
df.isnull().sum()
df['Unnamed: 1_level_0'].duplicated().sum()
duplicates=df[df.duplicated(subset=['Unnamed: 1_level_0'], keep=False)]
#print(duplicates)
print(duplicates['Unnamed: 1_level_0'].unique())

['Player' 'Cameron Archer' 'Armando Broja' 'Alex Iwobi' 'Brennan Johnson'
 'Neal Maupay' 'James Mcatee' 'Matheus Nunes' 'Cole Palmer'
 'Kalvin Phillips' 'Sergio Reguilón']

In [ ]:
df.drop_duplicates(subset=['Unnamed: 1_level_0'])

In [36]:
duplicates = df[df['Unnamed: 1_level_0'].isin(duplicates['Unnamed: 1_level_0'].unique())]
duplicates.tail(20)

,Unnamed: 0_level_0,Unnamed: 1_level_0,Unnamed: 2_level_0,Unnamed: 3_level_0,Unnamed: 4_level_0,Unnamed: 5_level_0,Unnamed: 6_level_0,Unnamed: 7_level_0,Standard,Standard.1,...,Standard.8,Standard.9,Standard.10,Standard.11,Expected,Expected.1,Expected.2,Expected.3,Expected.4,Unnamed: 25_level_0
351,338,James Mcatee,eng ENG,"MF,FW",Sheffield Utd,20,2002,20.2,3,25,...,18.6,2,1,1,3.1,2.3,0.09,-0.1,-0.3,Matches
352,339,James Mcatee,eng ENG,MF,Manchester City,20,2002,0.0,0,0,...,NaN,0,0,0,0.0,0.0,NaN,0.0,0.0,Matches
364,Rk,Player,Nation,Pos,Squad,Age,Born,90s,Gls,Sh,...,Dist,FK,PK,PKatt,xG,npxG,npxG/Sh,G-xG,np:G-xG,Matches
390,Rk,Player,Nation,Pos,Squad,Age,Born,90s,Gls,Sh,...,Dist,FK,PK,PKatt,xG,npxG,npxG/Sh,G-xG,np:G-xG,Matches
399,384,Matheus Nunes,pt POR,MF,Wolves,24,1998,2.0,0,1,...,15.4,0,0,0,0.1,0.1,0.08,-0.1,-0.1,Matches
400,385,Matheus Nunes,pt POR,MF,Manchester City,24,1998,7.3,0,9,...,17.9,0,0,0,0.8,0.8,0.09,-0.8,-0.8,Matches
416,Rk,Player,Nation,Pos,Squad,Age,Born,90s,Gls,Sh,...,Dist,FK,PK,PKatt,xG,npxG,npxG/Sh,G-xG,np:G-xG,Matches
430,414,Cole Palmer,eng ENG,"FW,MF",Chelsea,21,2002,29.0,22,100,...,22.1,11,9,9,18.2,11.1,0.11,+3.8,+1.9,Matches
431,415,Cole Palmer,eng ENG,MF,Manchester City,21,2002,0.1,0,0,...,NaN,0,0,0,0.0,0.0,NaN,0.0,0.0,Matches
442,Rk,Player,Nation,Pos,Squad,Age,Born,90s,Gls,Sh,...,Dist,FK,PK,PKatt,xG,npxG,npxG/Sh,G-xG,np:G-xG,Matches
444,427,Kalvin Phillips,eng ENG,MF,West Ham,27,1995,3.4,0,3,...,25.8,0,0,0,0.1,0.1,0.03,-0.1,-0.1,Matches
445,428,Kalvin Phillips,eng ENG,MF,Manchester City,27,1995,1.0,0,2,...,21.7,0,0,0,0.1,0.1,0.04,-0.1,-0.1,Matches
462,445,Sergio Reguilón,es ESP,DF,Manchester Utd,26,1996,4.6,0,4,...,18.1,0,0,0,0.2,0.2,0.05,-0.2,-0.2,Matches
463,446,Sergio Reguilón,es ESP,DF,Brentford,26,1996,12.4,0,13,...,18.2,0,0,0,0.8,0.8,0.06,-0.8,-0.8,Matches
468,Rk,Player,Nation,Pos,Squad,Age,Born,90s,Gls,Sh,...,Dist,FK,PK,PKatt,xG,npxG,npxG/Sh,G-xG,np:G-xG,Matches
494,Rk,Player,Nation,Pos,Squad,Age,Born,90s,Gls,Sh,...,Dist,FK,PK,PKatt,xG,npxG,npxG/Sh,G-xG,np:G-xG,Matches
520,Rk,Player,Nation,Pos,Squad,Age,Born,90s,Gls,Sh,...,Dist,FK,PK,PKatt,xG,npxG,npxG/Sh,G-xG,np:G-xG,Matches
546,Rk,Player,Nation,Pos,Squad,Age,Born,90s,Gls,Sh,...,Dist,FK,PK,PKatt,xG,npxG,npxG/Sh,G-xG,np:G-xG,Matches
572,Rk,Player,Nation,Pos,Squad,Age,Born,90s,Gls,Sh,...,Dist,FK,PK,PKatt,xG,npxG,npxG/Sh,G-xG,np:G-xG,Matches
598,Rk,Player,Nation,Pos,Squad,Age,Born,90s,Gls,Sh,...,Dist,FK,PK,PKatt,xG,npxG,npxG/Sh,G-xG,np:G-xG,Matches